name = "ct-registry"
uuid = "cbe350a3-3b6e-4d25-82e7-2ace49268c64"
repo = "https://github.com/control-toolbox/ct-registry"
description = "ct: control toolbox registry"

[packages]
1c39547c-7794-42f7-af83-d98194f657c2 = { name = "CTFlows", path = "C/CTFlows" }
32681960-a1b1-40db-9bff-a1ca817385d1 = { name = "CTParser", path = "C/CTParser" }
34c4fa32-2049-4079-8329-de33c2a22e2d = { name = "CTModels", path = "C/CTModels" }
790bbbee-bee9-49ee-8912-a9de031322d5 = { name = "CTDirect", path = "C/CTDirect" }
