name = "ct-registry"
uuid = "cbe350a3-3b6e-4d25-82e7-2ace49268c64"
repo = "https://github.com/control-toolbox/ct-registry"
description = "ct: control toolbox registry"

[packages]
34c4fa32-2049-4079-8329-de33c2a22e2d = { name = "CTModels", path = "C/CTModels" }
